site_name: MCP Gateway Masterclass
site_url: https://ruslanmv.github.io/mcp-gateway-workshop
site_author: Ruslan Magaña
site_description: Build governed, production-grade agentic AI with an MCP Gateway. Hands-on labs + capstone with CrewAI and Langflow.
repo_name: mcp-gateway-workshop
repo_url: https://github.com/ruslanmv/mcp-gateway-workshop
edit_uri: edit/main/docs

nav:
  - Home: index.md
  - Preface: preface.md
  - Syllabus: syllabus.md
  - Part I — Foundations: part1-foundations.md
  - Part II — Day-1 Labs: part2-labs.md
  - Part III — Capstone Theory: part3-capstone-theory.md
  - Part IV — Capstone Build: part4-capstone-build.md
  - Appendices:
      - Appendix A — Docling + watsonx.ai RAG via MCP Gateway: appendices/appendix-a-docling.md
      - Appendix B — Verified Commands & Config: appendices/appendix-b-verified-commands.md
      - Appendix C — API Usage Cheatsheet: appendices/appendix-c-api-cheatsheet.md
      - Appendix D — Troubleshooting & FAQ: appendices/appendix-d-troubleshooting.md
      - Appendix E — Screenshot Checklist: appendices/appendix-e-screenshot-checklist.md
      - Appendix F — Instructor Run-of-Show: appendices/appendix-f-instructor-ros.md
      - Appendix G — Kindle Production Tips: appendices/appendix-g-kindle-tips.md

theme:
  name: material
  custom_dir: docs/.overrides
  features:
    # Navigation & orientation
    - navigation.sections
    - navigation.path        # breadcrumbs
    - navigation.top         # back-to-top FAB
    - navigation.footer      # ← Previous | Next →
    - navigation.tracking    # sync sidebar with scroll
    # Content polish
    - content.code.copy
    - content.code.annotate
    - content.tabs.link
    - header.autohide        # sleek scrolling experience
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  icon:
    repo: fontawesome/brands/github

extra:
  hero_wallpaper: assets/images/mcp-wallpaper.jpg
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/ruslanmv/mcp-gateway-workshop

extra_css:
  - assets/css/wx-hero.css

extra_javascript:
  - assets/js/wx-hero.js
  - https://unpkg.com/mermaid@10/dist/mermaid.min.js

plugins:
  - search    # keep defaults for max compatibility in strict mode
  - social

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - md_in_html
  - def_list
  - footnotes
  - meta
  - toc:
      permalink: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tilde
