name: Docs (MkDocs → GitHub Pages)

on:
  push:
    branches: [ main, master ]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "README.md"
      - ".github/workflows/docs.yml"
  pull_request:
    branches: [ main, master ]
    paths:
      - "docs/**"
      - "mkdocs.yml"
      - "README.md"
  workflow_dispatch:

# Required permissions for GitHub Pages deployment
permissions:
  contents: read
  pages: write
  id-token: write

# Prevent concurrent deployments to Pages
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    name: Build MkDocs site
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install doc dependencies
        run: |
          python -m pip install --upgrade pip
          pip install \
            mkdocs \
            "mkdocs-material[imaging]" \
            mkdocs-macros-plugin \
            pymdown-extensions \
            mkdocs-mermaid2-plugin

      - name: Configure Pages
        uses: actions/configure-pages@v5

      - name: Build site (mkdocs)
        run: |
          mkdocs --version
          mkdocs build --strict

      - name: Upload Pages artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./site

  deploy:
    name: Deploy to GitHub Pages
    # Only deploy on push to default branch or manual dispatch; skip for PRs
    if: ${{ github.event_name != 'pull_request' }}
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy
        id: deployment
        uses: actions/deploy-pages@v4